### ISSUE TITLE
Join Shipment Item History with Shipment Item instead of Shipment Receipt in ShipmentAndItemAndReceipt

### ISSUE THREAD

**Issue by gawhadebhavna** [hotwax/ofbiz-oms-udm#75]
1. The ShipmentItemHistory should be joined with ShipmentItem instead of ShipmentReceipt as now we create history for all items irrespective of the receipt.
2. The assumption is that a shipment item can be received only once, so we should create history for all items in the shipment.

**Comment by gurveenbagga** [comment]
This is done as part of the PR, https://github.com/hotwax/ofbiz-oms-udm/pull/76
Closing this issue
